language: python

addons:
  postgresql: "9.4"
python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.11.*
  - DJANGO=2.0.*

matrix:
  include:
    - { python: 3.6, env: TOXENV=flake8 DJANGO=2.0.* }
    - { python: 3.6, env: TOXENV=isort DJANGO=2.0.* }

install:
  - pip install pipenv
  - pipenv install --system
  - pipenv install -d tox
  - pipenv install -d django==$DJANGO
  - pipenv install -d python-coveralls

script:
  - pipenv run tox

after_success:
  - coveralls
